name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


  workflow_dispatch:


jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: docker-compose up -d front
        
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  frontTests:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2


      - name: Tests in frontend App
        run: docker-compose run app bash -c "yarn install && yarn test:unit"

  frontCI:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2


      - name: Frontend Lint
        run: docker-compose run app bash -c "yarn install && yarn lint"